//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhuru.CloudFoundry.DEA.PluginBase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginBaseRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginBaseRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uhuru.CloudFoundry.DEA.PluginBase.Resources.PluginBaseRes", typeof(PluginBaseRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string HomeVariable {
            get {
                return ResourceManager.GetString("HomeVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_DEBUG_IP.
        /// </summary>
        internal static string VcapAppDebugIpVariable {
            get {
                return ResourceManager.GetString("VcapAppDebugIpVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_DEBUG_PORT.
        /// </summary>
        internal static string VcapAppDebugPortVariable {
            get {
                return ResourceManager.GetString("VcapAppDebugPortVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_APP_HOST.
        /// </summary>
        internal static string VcapAppHostVariable {
            get {
                return ResourceManager.GetString("VcapAppHostVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_APPLICATION.
        /// </summary>
        internal static string VcapApplicationVariable {
            get {
                return ResourceManager.GetString("VcapApplicationVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_APP_PID.
        /// </summary>
        internal static string VcapAppPidVariable {
            get {
                return ResourceManager.GetString("VcapAppPidVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_APP_PORT.
        /// </summary>
        internal static string VcapAppPortVariable {
            get {
                return ResourceManager.GetString("VcapAppPortVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_PLUGIN_STAGING_INFO.
        /// </summary>
        internal static string VcapPluginStagingInfoVariable {
            get {
                return ResourceManager.GetString("VcapPluginStagingInfoVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_SERVICES.
        /// </summary>
        internal static string VcapServicesVariable {
            get {
                return ResourceManager.GetString("VcapServicesVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_WINDOWS_USER_PASSWORD.
        /// </summary>
        internal static string VcapWindowsUserPasswordVariable {
            get {
                return ResourceManager.GetString("VcapWindowsUserPasswordVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_WINDOWS_USER.
        /// </summary>
        internal static string VcapWindowsUserVariable {
            get {
                return ResourceManager.GetString("VcapWindowsUserVariable", resourceCulture);
            }
        }
    }
}
