//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhuru.CloudFoundry.DEA.Plugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uhuru.CloudFoundry.DEA.Plugins.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App start operation exceeded maximum time.
        /// </summary>
        internal static string AppStartOperationExceeded {
            get {
                return ResourceManager.GetString("AppStartOperationExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument null or empty.
        /// </summary>
        internal static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring service .
        /// </summary>
        internal static string ConfiguringService {
            get {
                return ResourceManager.GetString("ConfiguringService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring service value: {0}.
        /// </summary>
        internal static string ConfiguringServiceValue {
            get {
                return ResourceManager.GetString("ConfiguringServiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied logging binaries to bin directory..
        /// </summary>
        internal static string CopiedLoggingBinariesToBin {
            get {
                return ResourceManager.GetString("CopiedLoggingBinariesToBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of a new config section not allowed..
        /// </summary>
        internal static string CreationOfNewConfigSection {
            get {
                return ResourceManager.GetString("CreationOfNewConfigSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying app on IIS..
        /// </summary>
        internal static string DeployingAppOnIis {
            get {
                return ResourceManager.GetString("DeployingAppOnIis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected CPU target runtime: {0}..
        /// </summary>
        internal static string DetectedCpuTarget {
            get {
                return ResourceManager.GetString("DetectedCpuTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected .Net application..
        /// </summary>
        internal static string DetectedNet {
            get {
                return ResourceManager.GetString("DetectedNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting CPU target runtime..
        /// </summary>
        internal static string DetectingCpuTarget {
            get {
                return ResourceManager.GetString("DetectingCpuTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining application framework version..
        /// </summary>
        internal static string DeterminingApplication {
            get {
                return ResourceManager.GetString("DeterminingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done setting up application variables..
        /// </summary>
        internal static string DoneSettingUpApplication {
            get {
                return ResourceManager.GetString("DoneSettingUpApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished app deployment on IIS.
        /// </summary>
        internal static string FinishedAppDeploymentOnIis {
            get {
                return ResourceManager.GetString("FinishedAppDeploymentOnIis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished starting IIS site.
        /// </summary>
        internal static string FinishedStartingIisSite {
            get {
                return ResourceManager.GetString("FinishedStartingIisSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {host}.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging auto-wiring only supports configuration from an external source at this time.
        /// </summary>
        internal static string LoggingAutoWiringOnly {
            get {
                return ResourceManager.GetString("LoggingAutoWiringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name}.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {password}.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {port}.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved configuration file..
        /// </summary>
        internal static string SavedConfigurationFile {
            get {
                return ResourceManager.GetString("SavedConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up application variables..
        /// </summary>
        internal static string SettingUpApplicationVariables {
            get {
                return ResourceManager.GetString("SettingUpApplicationVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up logging..
        /// </summary>
        internal static string SettingUpLogging {
            get {
                return ResourceManager.GetString("SettingUpLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site config: Configuration backup not implemented yet..
        /// </summary>
        internal static string SiteConfigConfiguration {
            get {
                return ResourceManager.GetString("SiteConfigConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting application auto-wiring..
        /// </summary>
        internal static string StartingApplicationAutoWiring {
            get {
                return ResourceManager.GetString("StartingApplicationAutoWiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting IIS site..
        /// </summary>
        internal static string StartingIisSite {
            get {
                return ResourceManager.GetString("StartingIisSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated logging configuration settings..
        /// </summary>
        internal static string UpdatedLoggingConfiguration {
            get {
                return ResourceManager.GetString("UpdatedLoggingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user}.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
