//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhuru.CloudFoundry.ServiceBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uhuru.CloudFoundry.ServiceBase.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Bind request: {1} from {2}.
        /// </summary>
        internal static string BindRequestLogMessage {
            get {
                return ResourceManager.GetString("BindRequestLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception at OnCheckOrphan {0}.
        /// </summary>
        internal static string CheckOrphanExceptionLogMessage {
            get {
                return ResourceManager.GetString("CheckOrphanExceptionLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: handles for checking orphan.
        /// </summary>
        internal static string CheckOrphanLogMessage {
            get {
                return ResourceManager.GetString("CheckOrphanLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: cleanup nfs request {1} from {2}.
        /// </summary>
        internal static string CleanupNfsLogMessage {
            get {
                return ResourceManager.GetString("CleanupNfsLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Connected to node mbus.
        /// </summary>
        internal static string ConnectedLogMessage {
            get {
                return ResourceManager.GetString("ConnectedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Initializing.
        /// </summary>
        internal static string InitializingLogMessage {
            get {
                return ResourceManager.GetString("InitializingLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.bind.{1}.
        /// </summary>
        internal static string NatsSubjectBind {
            get {
                return ResourceManager.GetString("NatsSubjectBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.check_orphan.
        /// </summary>
        internal static string NatsSubjectCheckOrphan {
            get {
                return ResourceManager.GetString("NatsSubjectCheckOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.cleanup_nfs.{1}.
        /// </summary>
        internal static string NatsSubjectCleanupNfs {
            get {
                return ResourceManager.GetString("NatsSubjectCleanupNfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.disable_instance.{1}.
        /// </summary>
        internal static string NatsSubjectDisableInstance {
            get {
                return ResourceManager.GetString("NatsSubjectDisableInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.discover.
        /// </summary>
        internal static string NatsSubjectDiscover {
            get {
                return ResourceManager.GetString("NatsSubjectDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.enable_instance.{1}.
        /// </summary>
        internal static string NatsSubjectEnableInstance {
            get {
                return ResourceManager.GetString("NatsSubjectEnableInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.import_instance.{1}.
        /// </summary>
        internal static string NatsSubjectImportInstance {
            get {
                return ResourceManager.GetString("NatsSubjectImportInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.orphan_result.
        /// </summary>
        internal static string NatsSubjectOrphanResult {
            get {
                return ResourceManager.GetString("NatsSubjectOrphanResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.provision.{1}.
        /// </summary>
        internal static string NatsSubjectProvision {
            get {
                return ResourceManager.GetString("NatsSubjectProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.purge_orphan.{1}.
        /// </summary>
        internal static string NatsSubjectPurgeOrphan {
            get {
                return ResourceManager.GetString("NatsSubjectPurgeOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.restore.{1}.
        /// </summary>
        internal static string NatsSubjectRestore {
            get {
                return ResourceManager.GetString("NatsSubjectRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.unprovision.{1}.
        /// </summary>
        internal static string NatsSubjectUnprovision {
            get {
                return ResourceManager.GetString("NatsSubjectUnprovision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Shutting down.
        /// </summary>
        internal static string ShuttingDownLogMessage {
            get {
                return ResourceManager.GetString("ShuttingDownLogMessage", resourceCulture);
            }
        }
    }
}
