//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhuru.CloudFoundry.DEA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uhuru.CloudFoundry.DEA.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual usage was {0}M, process terminated..
        /// </summary>
        internal static string ActualUsageWasProcessTerminated {
            get {
                return ResourceManager.GetString("ActualUsageWasProcessTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowing multi-tenancy.
        /// </summary>
        internal static string Allowingmultitenancy {
            get {
                return ResourceManager.GetString("Allowingmultitenancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; app instance &apos;{1}&apos; is not detected to be running. App considered crashes and stoping instance....
        /// </summary>
        internal static string AppNotDetectedReady {
            get {
                return ResourceManager.GetString("AppNotDetectedReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps.du.{0}.details.
        /// </summary>
        internal static string AppsDuDetails {
            get {
                return ResourceManager.GetString("AppsDuDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps.du.{0}.summary.
        /// </summary>
        internal static string AppsDuSummary {
            get {
                return ResourceManager.GetString("AppsDuSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye...
        /// </summary>
        internal static string ByeMessage {
            get {
                return ResourceManager.GetString("ByeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create supported directories: {0}.
        /// </summary>
        internal static string CannotCreateSupported {
            get {
                return ResourceManager.GetString("CannotCreateSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t determine application runtimes, exiting.
        /// </summary>
        internal static string CannotDetermineApplicationRuntimes {
            get {
                return ResourceManager.GetString("CannotDetermineApplicationRuntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cd /D {0}.
        /// </summary>
        internal static string CdCommand {
            get {
                return ResourceManager.GetString("CdCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking runtimes....
        /// </summary>
        internal static string Checkingruntimes {
            get {
                return ResourceManager.GetString("Checkingruntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Cleaned up dir {1}.
        /// </summary>
        internal static string CleandUpDir {
            get {
                return ResourceManager.GetString("CleandUpDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients: {0}.
        /// </summary>
        internal static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud not clean cache directory: {0}.
        /// </summary>
        internal static string CloudNotCleanCacheDirectory {
            get {
                return ResourceManager.GetString("CloudNotCleanCacheDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud not remove instance: {0}, error: {1}.
        /// </summary>
        internal static string CloudNotRemoveInstance {
            get {
                return ResourceManager.GetString("CloudNotRemoveInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud not start, runtime not supported. ({0}).
        /// </summary>
        internal static string CloudNotStartRuntimeNot {
            get {
                return ResourceManager.GetString("CloudNotStartRuntimeNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} completed running with status = {1}..
        /// </summary>
        internal static string CompletedRunningWith {
            get {
                return ResourceManager.GetString("CompletedRunningWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crashes reaper deleted: {0}.
        /// </summary>
        internal static string CrashesReaperDeleted {
            get {
                return ResourceManager.GetString("CrashesReaperDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d:{1}h:{2}m:{3}s.
        /// </summary>
        internal static string DaysHoursMinutesSecondsDateTimeFormat {
            get {
                return ResourceManager.GetString("DaysHoursMinutesSecondsDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA received discovery message: {0}.
        /// </summary>
        internal static string DeaReceivedDiscoveryMessage {
            get {
                return ResourceManager.GetString("DeaReceivedDiscoveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA received find droplet message: {0}.
        /// </summary>
        internal static string DeaReceivedFindDroplet {
            get {
                return ResourceManager.GetString("DeaReceivedFindDroplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA received healthmanager start message: {0}.
        /// </summary>
        internal static string DeaReceivedHealthmanagerStart {
            get {
                return ResourceManager.GetString("DeaReceivedHealthmanagerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA received router start message: {0}.
        /// </summary>
        internal static string DeaReceivedRouterStart {
            get {
                return ResourceManager.GetString("DeaReceivedRouterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA received start message: {0}.
        /// </summary>
        internal static string DeaReceivedStartMessage {
            get {
                return ResourceManager.GetString("DeaReceivedStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA received status message.
        /// </summary>
        internal static string DEAreceivedstatusmessage {
            get {
                return ResourceManager.GetString("DEAreceivedstatusmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA received stop message: {0}.
        /// </summary>
        internal static string DeaReceivedStopMessage {
            get {
                return ResourceManager.GetString("DeaReceivedStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA received update message: {0}.
        /// </summary>
        internal static string DeaReceivedUpdateMessage {
            get {
                return ResourceManager.GetString("DeaReceivedUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA recovered {0} applications.
        /// </summary>
        internal static string DeaRecoveredApplications {
            get {
                return ResourceManager.GetString("DeaRecoveredApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk usage limit of {0}M exceeded..
        /// </summary>
        internal static string DiskUsageLimitOf {
            get {
                return ResourceManager.GetString("DiskUsageLimitOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donloded file from {0} is corrupt: {1} != {2}.
        /// </summary>
        internal static string DonlodedFileFromIs {
            get {
                return ResourceManager.GetString("DonlodedFileFromIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have room for this client application.
        /// </summary>
        internal static string Donothaveroomforthisclient {
            get {
                return ResourceManager.GetString("Donothaveroomforthisclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download compleate.
        /// </summary>
        internal static string Downloadcompleate {
            get {
                return ResourceManager.GetString("Downloadcompleate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloded file is corrupt..
        /// </summary>
        internal static string Downlodedfileiscorrupt {
            get {
                return ResourceManager.GetString("Downlodedfileiscorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error recovering droplet {0}. Exception: {1}.
        /// </summary>
        internal static string ErrorRecoveringDropletWarningMessage {
            get {
                return ResourceManager.GetString("ErrorRecoveringDropletWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping droplet: {0}, instance: {1}, exception:.
        /// </summary>
        internal static string ErrorStoppingDropletErrorMessage {
            get {
                return ResourceManager.GetString("ErrorStoppingDropletErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuating app {0}.
        /// </summary>
        internal static string EvacuatingApp {
            get {
                return ResourceManager.GetString("EvacuatingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuating applications...
        /// </summary>
        internal static string Evacuatingapplications {
            get {
                return ResourceManager.GetString("Evacuatingapplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXITING! Nats error: {0}.
        /// </summary>
        internal static string ExitingNatsError {
            get {
                return ResourceManager.GetString("ExitingNatsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FAILED, additional checks failed.
        /// </summary>
        internal static string FailedAdditionalChecks {
            get {
                return ResourceManager.GetString("FailedAdditionalChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FAILED, executable &apos;{1}&apos; not found 
        /// Current directory: {2} 
        /// Full executable path: {3}.
        /// </summary>
        internal static string FailedExecutableNot {
            get {
                return ResourceManager.GetString("FailedExecutableNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed staging app dir &apos;{0}&apos;, not starting app {1}, Exception: {2}.
        /// </summary>
        internal static string FailedStagingAppDir {
            get {
                return ResourceManager.GetString("FailedStagingAppDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FAILED, version mismatch ({1}).
        /// </summary>
        internal static string FailedVersionMismatch {
            get {
                return ResourceManager.GetString("FailedVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer service failed to start: {0} already in use?: {1}.
        /// </summary>
        internal static string FilerServiceFailedToStart {
            get {
                return ResourceManager.GetString("FilerServiceFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File service started on port: {0}.
        /// </summary>
        internal static string FileServiceStartedOnPort {
            get {
                return ResourceManager.GetString("FileServiceStartedOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found staged bits in local cache..
        /// </summary>
        internal static string FoundStagedBitsInLocalCache {
            get {
                return ResourceManager.GetString("FoundStagedBitsInLocalCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giving up detecting stop file.
        /// </summary>
        internal static string GivingUpDetectingStopFile {
            get {
                return ResourceManager.GetString("GivingUpDetectingStopFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giving up on connecting app.
        /// </summary>
        internal static string GivingUpOnConnectingApp {
            get {
                return ResourceManager.GetString("GivingUpOnConnectingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giving up on trying to start filer, exiting....
        /// </summary>
        internal static string GivingUpOnTryingToStartFiler {
            get {
                return ResourceManager.GetString("GivingUpOnTryingToStartFiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME={0}.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}:{1}/droplets/.
        /// </summary>
        internal static string HttpDroplets {
            get {
                return ResourceManager.GetString("HttpDroplets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring request..
        /// </summary>
        internal static string IgnoringRequest {
            get {
                return ResourceManager.GetString("IgnoringRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring request, no suitable runtimes available for &apos;{0}&apos;.
        /// </summary>
        internal static string IgnoringRequestNoSuitableRuntimes {
            get {
                return ResourceManager.GetString("IgnoringRequestNoSuitableRuntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring request, not enough memory.
        /// </summary>
        internal static string IgnoringRequestNotEnoughMemory {
            get {
                return ResourceManager.GetString("IgnoringRequestNotEnoughMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring request, {0} runtime not supported.
        /// </summary>
        internal static string IgnoringRequestRuntime {
            get {
                return ResourceManager.GetString("IgnoringRequestRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring request, runtime not enabled for &apos;{0}&apos;.
        /// </summary>
        internal static string IgnoringRequestRuntimeNot {
            get {
                return ResourceManager.GetString("IgnoringRequestRuntimeNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance {0} is ready for connections, notifying system of status.
        /// </summary>
        internal static string InstanceIsReadyForConnections {
            get {
                return ResourceManager.GetString("InstanceIsReadyForConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} instance process could not be added to the instance job object: {1}.
        /// </summary>
        internal static string InstanceProcessCoudNotBeAdded {
            get {
                return ResourceManager.GetString("InstanceProcessCoudNotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowering instance process priority to: {0}.
        /// </summary>
        internal static string LoggerLoweringPriority {
            get {
                return ResourceManager.GetString("LoggerLoweringPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowering priority on CPU bound process({0}), new value:{1}.
        /// </summary>
        internal static string LoweringPriorityOnCpuBound {
            get {
                return ResourceManager.GetString("LoweringPriorityOnCpuBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping new URIs.
        /// </summary>
        internal static string MappingnewURIs {
            get {
                return ResourceManager.GetString("MappingnewURIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max memory set to {0}M.
        /// </summary>
        internal static string MaxMemorySetTo {
            get {
                return ResourceManager.GetString("MaxMemorySetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory limit of {0}M exceeded..
        /// </summary>
        internal static string MemoryLimitOfExceeded {
            get {
                return ResourceManager.GetString("MemoryLimitOfExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Monitor App Exception: {0}&quot;.
        /// </summary>
        internal static string MonitorException {
            get {
                return ResourceManager.GetString("MonitorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name={0} app_id={1} instance={2} index={3}.
        /// </summary>
        internal static string NameAppIdInstance {
            get {
                return ResourceManager.GetString("NameAppIdInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nats error: {0}.
        /// </summary>
        internal static string NatsError {
            get {
                return ResourceManager.GetString("NatsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dea.{0}.sentinel.
        /// </summary>
        internal static string NatsMessageDeaSentinel {
            get {
                return ResourceManager.GetString("NatsMessageDeaSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dea.{0}.start.
        /// </summary>
        internal static string NatsMessageDeaStart {
            get {
                return ResourceManager.GetString("NatsMessageDeaStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vcap.component.announce.
        /// </summary>
        internal static string NatsSubjectVcapComponentAnnounce {
            get {
                return ResourceManager.GetString("NatsSubjectVcapComponentAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vcap.component.discover.
        /// </summary>
        internal static string NatsSubjectVcapComponentDiscover {
            get {
                return ResourceManager.GetString("NatsSubjectVcapComponentDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to download app bits from {0}.
        /// </summary>
        internal static string Needtodownloadappbitsfrom {
            get {
                return ResourceManager.GetString("Needtodownloadappbitsfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New: {0} Current: {1}.
        /// </summary>
        internal static string NewCurrent {
            get {
                return ResourceManager.GetString("NewCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID:{0} assigned to droplet instance: {1}.
        /// </summary>
        internal static string PidAssignedToDroplet {
            get {
                return ResourceManager.GetString("PidAssignedToDroplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing instance &apos;{0}&apos;, doesn&apos;t correspond to any instance entry..
        /// </summary>
        internal static string RemovingInstanceDoesn {
            get {
                return ResourceManager.GetString("RemovingInstanceDoesn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved Memory Usage: {0} MB of {1} MB TOTAL.
        /// </summary>
        internal static string ReservedMemoryUsageMb {
            get {
                return ResourceManager.GetString("ReservedMemoryUsageMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricting to single tenant.
        /// </summary>
        internal static string RestrictingToSingleTenant {
            get {
                return ResourceManager.GetString("RestrictingToSingleTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} OK.
        /// </summary>
        internal static string RuntimeOk {
            get {
                return ResourceManager.GetString("RuntimeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling shutdown in {0} seconds...
        /// </summary>
        internal static string SchedulingShutdownIn {
            get {
                return ResourceManager.GetString("SchedulingShutdownIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending dea.discover response message with a taint delay of: {0} ms.
        /// </summary>
        internal static string SendingDeaDiscoverResponse {
            get {
                return ResourceManager.GetString("SendingDeaDiscoverResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent droplet.exited {0}.
        /// </summary>
        internal static string SentDropletExited {
            get {
                return ResourceManager.GetString("SentDropletExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set {0}.
        /// </summary>
        internal static string SetCommand {
            get {
                return ResourceManager.GetString("SetCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing cloud controller&apos;s staging directory.
        /// </summary>
        internal static string SharingCloudControllerStagingDirectory {
            get {
                return ResourceManager.GetString("SharingCloudControllerStagingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down...
        /// </summary>
        internal static string ShuttingDownMessage {
            get {
                return ResourceManager.GetString("ShuttingDownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snap_{0}.
        /// </summary>
        internal static string SnapshotTemplate {
            get {
                return ResourceManager.GetString("SnapshotTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting up instance {0} on port {1} .
        /// </summary>
        internal static string StartingUpInstanceOnPort {
            get {
                return ResourceManager.GetString("StartingUpInstanceOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting VCAP DEA {0}.
        /// </summary>
        internal static string StartingVcapDea {
            get {
                return ResourceManager.GetString("StartingVcapDea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start request missing proper download information, ignoring request. ({0}).
        /// </summary>
        internal static string StartRequestMissingProper {
            get {
                return ResourceManager.GetString("StartRequestMissingProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop operation completed running with status = {0}..
        /// </summary>
        internal static string Stopoperationcompletedrunning {
            get {
                return ResourceManager.GetString("Stopoperationcompletedrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop operation std output is: {0}.
        /// </summary>
        internal static string StopOperationStdOutputIs {
            get {
                return ResourceManager.GetString("StopOperationStdOutputIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping instance {0}.
        /// </summary>
        internal static string StoppingInstance {
            get {
                return ResourceManager.GetString("StoppingInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0} to copy from shared directory.
        /// </summary>
        internal static string TookXSecondsToCopyFromShared {
            get {
                return ResourceManager.GetString("TookXSecondsToCopyFromShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0} to download and write file.
        /// </summary>
        internal static string TookXSecondsToDownloadAndWrite {
            get {
                return ResourceManager.GetString("TookXSecondsToDownloadAndWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0}s to execute du..
        /// </summary>
        internal static string TookXSecondsToExecuteDu {
            get {
                return ResourceManager.GetString("TookXSecondsToExecuteDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0}s to execute ps. ({1} entries returned).
        /// </summary>
        internal static string TookXSecondsToExecutePs {
            get {
                return ResourceManager.GetString("TookXSecondsToExecutePs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0}s to process ps and du stats.
        /// </summary>
        internal static string TookXSecondsToProcessPsAndDu {
            get {
                return ResourceManager.GetString("TookXSecondsToProcessPsAndDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0} to snapshot application state..
        /// </summary>
        internal static string TookXSecondsToSnapshotApplication {
            get {
                return ResourceManager.GetString("TookXSecondsToSnapshotApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0} to stage the app directory.
        /// </summary>
        internal static string TookXSecondsToStageTheApp {
            get {
                return ResourceManager.GetString("TookXSecondsToStageTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0} to load the plugin, configure the application, and start it..
        /// </summary>
        internal static string TookXTimeToLoadConfigureAndStartDebugMessage {
            get {
                return ResourceManager.GetString("TookXTimeToLoadConfigureAndStartDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete directory {0}, UnauthorizedAccessException: {1}.
        /// </summary>
        internal static string UnableToDeleteDirectory {
            get {
                return ResourceManager.GetString("UnableToDeleteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} uptime was {1}..
        /// </summary>
        internal static string UptimeWas {
            get {
                return ResourceManager.GetString("UptimeWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directory {0}.
        /// </summary>
        internal static string UsingDirectory {
            get {
                return ResourceManager.GetString("UsingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using network {0}.
        /// </summary>
        internal static string UsingNetwork {
            get {
                return ResourceManager.GetString("UsingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizing {0} cpu cores.
        /// </summary>
        internal static string UtilizingCpuCores {
            get {
                return ResourceManager.GetString("UtilizingCpuCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_APP_HOST=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVcapAppHost {
            get {
                return ResourceManager.GetString("VariableVcapAppHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_APPLICATION=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVcapApplication {
            get {
                return ResourceManager.GetString("VariableVcapApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_APP_PORT=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVcapAppPort {
            get {
                return ResourceManager.GetString("VariableVcapAppPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_DEBUG_IP=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVcapDebugIp {
            get {
                return ResourceManager.GetString("VariableVcapDebugIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_DEBUG_PORT=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVcapDebugPort {
            get {
                return ResourceManager.GetString("VariableVcapDebugPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCAP_SERVICES=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVcapServices {
            get {
                return ResourceManager.GetString("VariableVcapServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMC_{0}={1}:{2}.
        /// </summary>
        internal static string VariableVmc {
            get {
                return ResourceManager.GetString("VariableVmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMC_APP_HOST=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVmcAppHost {
            get {
                return ResourceManager.GetString("VariableVmcAppHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMC_APP_ID=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVmcAppId {
            get {
                return ResourceManager.GetString("VariableVmcAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMC_APP_INSTANCE=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVmcAppInstance {
            get {
                return ResourceManager.GetString("VariableVmcAppInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMC_APP_NAME=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVmcAppName {
            get {
                return ResourceManager.GetString("VariableVmcAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMC_APP_PORT=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVmcAppPort {
            get {
                return ResourceManager.GetString("VariableVmcAppPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMC_APP_VERSION=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVmcAppVersion {
            get {
                return ResourceManager.GetString("VariableVmcAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMC_WARNING_WARNING=&apos;All VMC_* environment variables are deprecated, please use VCAP_* versions.&apos;.
        /// </summary>
        internal static string VariableVmcDeprecatedWarning {
            get {
                return ResourceManager.GetString("VariableVmcDeprecatedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMC_SERVICES=&apos;{0}&apos;.
        /// </summary>
        internal static string VariableVmcServices {
            get {
                return ResourceManager.GetString("VariableVmcServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with debugger port {0}.
        /// </summary>
        internal static string WithDebuggerPort {
            get {
                return ResourceManager.GetString("WithDebuggerPort", resourceCulture);
            }
        }
    }
}
