//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhuru.CloudFoundry.DEA.DirectoryServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uhuru.CloudFoundry.DEA.DirectoryServer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t serve request due to error: {0}.
        /// </summary>
        internal static string CantServeRequest {
            get {
                return ResourceManager.GetString("CantServeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dea did not respond with 200 status.
        /// </summary>
        internal static string DeaBadStatus {
            get {
                return ResourceManager.GetString("DeaBadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dea responded with invalid json.
        /// </summary>
        internal static string DeaInvalidJson {
            get {
                return ResourceManager.GetString("DeaInvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dea is unreachable.
        /// </summary>
        internal static string DeaUnreachable {
            get {
                return ResourceManager.GetString("DeaUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.\n.
        /// </summary>
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while dumping file. {0}.
        /// </summary>
        internal static string ErrorDumpingFile {
            get {
                return ResourceManager.GetString("ErrorDumpingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in LookupPath: {0}.
        /// </summary>
        internal static string ErrorInLookupPath {
            get {
                return ResourceManager.GetString("ErrorInLookupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to setup file system watcher - {0}.
        /// </summary>
        internal static string ErrorSettingUpFileSystemWatcher {
            get {
                return ResourceManager.GetString("ErrorSettingUpFileSystemWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while writing file. {0}.
        /// </summary>
        internal static string ErrorWritingFile {
            get {
                return ResourceManager.GetString("ErrorWritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Listener Error - {0}.
        /// </summary>
        internal static string HttpListenerError {
            get {
                return ResourceManager.GetString("HttpListenerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} not found..
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows DEA did not respond properly..
        /// </summary>
        internal static string WinDEADidNotRespondProperly {
            get {
                return ResourceManager.GetString("WinDEADidNotRespondProperly", resourceCulture);
            }
        }
    }
}
