//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhuru.ResqueClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Keys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uhuru.ResqueClient.Keys", typeof(Keys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:failed.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:queue:{0}.
        /// </summary>
        internal static string PopQueue {
            get {
                return ResourceManager.GetString("PopQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:workers.
        /// </summary>
        internal static string RegisterWorker {
            get {
                return ResourceManager.GetString("RegisterWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:stat:failed.
        /// </summary>
        internal static string StatFailed {
            get {
                return ResourceManager.GetString("StatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:stat:failed:{0}.
        /// </summary>
        internal static string StatFailedWorkerId {
            get {
                return ResourceManager.GetString("StatFailedWorkerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:stat:processed.
        /// </summary>
        internal static string StatProcessed {
            get {
                return ResourceManager.GetString("StatProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:stat:processed:{0}.
        /// </summary>
        internal static string StatProcessedWorkerId {
            get {
                return ResourceManager.GetString("StatProcessedWorkerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:worker.
        /// </summary>
        internal static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:worker:{0}.
        /// </summary>
        internal static string WorkerId {
            get {
                return ResourceManager.GetString("WorkerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resque:worker:{0}:started.
        /// </summary>
        internal static string WorkerIdStarted {
            get {
                return ResourceManager.GetString("WorkerIdStarted", resourceCulture);
            }
        }
    }
}
