// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "CloudFoundry.Net.Test.Automation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#AddDeleteUserTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#CreateServiceTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#FrameworksTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#LoginTestBad()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#ProvisionedServicesTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#RuntimesTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#ServicesTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#TestFixtureSetUp()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#TestFixtureTearDown()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#UsersTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#LogOnTestBad()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#LogOnTestOk()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#TestFixtureSetup()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#RunVMCTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#RunUserOperationsTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "NUnit.Framework.Assert.IsTrue(System.Boolean,System.String)", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#RunUserOperationsTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#RunTargetTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#GetServicesTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "NUnit.Framework.Assert.IsTrue(System.Boolean,System.String)", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#GetServicesTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#GetProvisionedServicesTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "NUnit.Framework.Assert.IsTrue(System.Boolean,System.String)", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#GetProvisionedServicesTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.CFApiTest.#TestFixtureTeardown()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TestUmbraco(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#GetAppsTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.Helper.#InternetSetOption(System.IntPtr,System.Int32,System.IntPtr,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.Helper.#SetProxy(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.Helper.#UnsetProxy()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC001_DatabaseCreate()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC002_DatabaseDelete()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC003_3Secquential()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC004_5Parallel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC005_16Parallel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TestFixtureSetup()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TestFixtureTeardown()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TC001_Create_UmbracoSimple()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TC002_Delete_UmbracoSimple()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TC004_Create_5Parallel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TestFixtureSetUp()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TestFixtureTearDown()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TestUmbraco(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TC003_Create_3Secquential()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC001_DatabaseCreate()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC002_DatabaseDelete()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC003_3Secquential()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC004_5Parallel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC005_16Parallel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TC001_Create_UmbracoSimple()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TC002_Delete_UmbracoSimple()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TC003_Create_3Secquential()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TC004_Create_5Parallel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TestUmbraco(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "NUnit.Framework.Assert.Inconclusive(System.String)", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.MsSqlServicesTest.#TC005_16Parallel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "NUnit.Framework.Assert.Inconclusive(System.String)", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.UmbracoTest.#TC004_Create_5Parallel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "NUnit.Framework.Assert.IsTrue(System.Boolean,System.String)", Scope = "member", Target = "CloudFoundry.Net.Test.Automation.VmcClientTests.#GetAppsTest()")]
