//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhuru.NatsClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uhuru.NatsClient.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to reconnect to the NATS server..
        /// </summary>
        internal static string AttemptingReconnect {
            get {
                return ResourceManager.GetString("AttemptingReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception in the callback..
        /// </summary>
        internal static string CallbackException {
            get {
                return ResourceManager.GetString("CallbackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to server.
        /// </summary>
        internal static string ERRCanNotConnect {
            get {
                return ResourceManager.GetString("ERRCanNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown protocol.
        /// </summary>
        internal static string ERRUnknownProtocol {
            get {
                return ResourceManager.GetString("ERRUnknownProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asyncResult parameter is null.\r\n.
        /// </summary>
        internal static string ExceptionAsyncResultParameterNull {
            get {
                return ResourceManager.GetString("ExceptionAsyncResultParameterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer offset or size is incorrect.\r\n.
        /// </summary>
        internal static string ExceptionBufferOffsetOrSizeIncorrect {
            get {
                return ResourceManager.GetString("ExceptionBufferOffsetOrSizeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer parameter is null.\r\n.
        /// </summary>
        internal static string ExceptionMessageBufferParameterNull {
            get {
                return ResourceManager.GetString("ExceptionMessageBufferParameterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network stream is closed.\r\n.
        /// </summary>
        internal static string ExceptionNetworkStreamClosed {
            get {
                return ResourceManager.GetString("ExceptionNetworkStreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem reading from the socket.\r\n.
        /// </summary>
        internal static string ExceptionSocketReadProblem {
            get {
                return ResourceManager.GetString("ExceptionSocketReadProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATS ReadTCPData failed..
        /// </summary>
        internal static string ReadTCPDataException {
            get {
                return ResourceManager.GetString("ReadTCPDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATS SendData failed: {0}.
        /// </summary>
        internal static string SendDataFailed {
            get {
                return ResourceManager.GetString("SendDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reconnect to NATS server..
        /// </summary>
        internal static string UnableToReconnect {
            get {
                return ResourceManager.GetString("UnableToReconnect", resourceCulture);
            }
        }
    }
}
